### ISSUE TITLE
Allow Artisan causing errors when pawns try to craft wooden type floors.

### ISSUE THREAD

**Issue by Amnesiac9** [Jaxe-Dev/PawnRules#3]
If a pawn is set to disallow Artisan Crafting with the mod, they cannot craft any wooden floors, even though the floors should not be marked as "Artisan" since they don't have a quality level like a chair or table does.

When a pawn is set to not allow Artisan Crafting, it throws this error:

When trying to right click force work on floors:
https://git.io/fAFEW
Pic: https://i.imgur.com/crmUl6f.png

When pawn naturally tries to work on floors:
https://git.io/fAFEl

I'm not sure why, If I can provide more info or help in any way, please let me know. I'd love to use both these mods without having to allow all my workers to construct artisan structures.

These errors were generated when I had a ton of mods, but I got the same errors when I loaded only this mod and Hugslib:

When Force: https://git.io/fAFgL
When they try to build them naturally: https://git.io/fAFgq

**Comment by Jaxe-Dev** [comment]
Thank you for the report, fixed in v1.1.5
